---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: azure.csi.confidential.cloud
parameters:
  skuName: StandardSSD_LRS  # alias: storageaccounttype, available values: Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer  # available values: "WaitForFirstConsumer", "Immediate"
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.azure.csi.confidential.cloud/zone
        values:
          - eastus2-1
          - eastus2-2
---
