---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: azuredisk.csi.confidential.cloud
parameters:
  skuName: StandardSSD_LRS  # alias: storageaccounttype, available values: Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS
reclaimPolicy: Delete
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.azuredisk.csi.confidential.cloud/zone
        values:
          - eastus2-1
---
