---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: azuredisk.csi.confidential.cloud
  annotations:
    csiDriver: v1.9.0
    snapshot: v3.0.3
spec:
  attachRequired: true
  podInfoOnMount: false
