name: Build and upload CSI driver container image

on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: "Version tag of the image"
        default: "latest"
        type: string
        required: true

jobs:
  build-csi-driver:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.1.0

      - name: Install Go
        uses: actions/setup-go@v3.4.0
        with:
          go-version: "1.18"

      - name: Set up Docker Buildx
        id: docker-setup
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9

      - name: Build container image
        run: |
          make PUBLISH=true REGISTRY=ghcr.io/edgelesssys IMAGE_NAME=constellation/azure-csi-driver IMAGE_VERSION=${{ inputs.versionTag }} container
          docker image ls

      - name: Log in to the Container registry
        id: docker-login
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container image
        run: docker push ghcr.io/edgelesssys/constellation/azure-csi-driver:${{ inputs.versionTag }}
