name: Linux Build & Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.1.0

      - name: Set up Go
        uses: actions/setup-go@v3.4.0
        with:
          go-version: 1.18
        id: go

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libcryptsetup-dev

      - name: Build Test
        run: |
          go test -covermode=count -coverprofile=profile.cov ./pkg/...
