name: Linux Build & Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
        id: go

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libcryptsetup-dev

      - name: Build Test
        run: go test -race -covermode=atomic -coverprofile=profile.cov ./pkg/...
