name: Static Checks
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  # pull_request:
jobs:
  go_lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.20.3"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get -y install libcryptsetup-dev

      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
