name: Static Checks
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  go_lint:
    name: Go Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: -E=gofmt --timeout=30m0s -E=deadcode -E=unused -E=varcheck -E=ineffassign
